import { PaymentPlan } from '../types/payment';
import { MoneyCircle } from '../types/circle';
import { SavingsGoal, SavingsAchievement } from '../types/goal';
import { AppNotification, NotificationPreferences } from '../types/notification';

export const INITIAL_USER = {
  id: 'user_sourav_1',
  name: 'Sourav Kumar',
  email: 'sourav@example.com',
  currency: '₹',
  availableBalance: 24892.9,
  monthlyIncome: 40000,
  plannedExpenses: 8000,
  savingsTarget: 5000,
};

export const INITIAL_NOTIFICATION_PREFERENCES: NotificationPreferences = {
  paymentReminders: true,
  paymentSuccessful: true,
  overduePayments: true,
  circleMemberPayments: true,
  savingsUpdates: false,
  weeklySummary: true,
  emailNotifications: true,
  pushNotifications: true,
};

// Generate relative dates for realistic presentation
const now = new Date();
const currentYear = now.getFullYear();
const currentMonth = String(now.getMonth() + 1).padStart(2, '0');
const prevMonth = String(now.getMonth() === 0 ? 12 : now.getMonth()).padStart(2, '0');
const prevYear = now.getMonth() === 0 ? currentYear - 1 : currentYear;

export const INITIAL_PAYMENT_PLANS: PaymentPlan[] = [
  {
    id: 'plan_bike_emi',
    userId: 'user_sourav_1',
    title: 'Bike EMI',
    description: 'HDFC Two Wheeler Loan',
    amount: 5000,
    category: 'emi',
    frequency: 'monthly',
    startDate: `${currentYear}-01-10`,
    endDate: `${currentYear + 2}-01-10`,
    totalCycles: 24,
    dueDay: 10,
    paymentMethod: 'UPI',
    reminderDaysBefore: 3,
    status: 'active',
    createdAt: `${currentYear}-01-01`,
    cycles: [
      {
        id: 'c_bike_1',
        paymentPlanId: 'plan_bike_emi',
        cycleNumber: 7,
        dueDate: `${prevYear}-${prevMonth}-10`,
        amount: 5000,
        status: 'paid',
        paidAt: `${prevYear}-${prevMonth}-09`,
        paymentMethod: 'UPI',
        referenceNumber: 'UPI98421049281',
      },
      {
        id: 'c_bike_2',
        paymentPlanId: 'plan_bike_emi',
        cycleNumber: 8,
        dueDate: `${currentYear}-${currentMonth}-10`,
        amount: 5000,
        status: 'due_soon',
        paymentMethod: 'UPI',
      },
      {
        id: 'c_bike_3',
        paymentPlanId: 'plan_bike_emi',
        cycleNumber: 9,
        dueDate: `${currentYear}-${String(now.getMonth() + 2).padStart(2, '0')}-10`,
        amount: 5000,
        status: 'upcoming',
        paymentMethod: 'UPI',
      },
    ],
  },
  {
    id: 'plan_rent',
    userId: 'user_sourav_1',
    title: 'Apartment Rent',
    description: 'Monthly flat rent transfer',
    amount: 10000,
    category: 'housing',
    frequency: 'monthly',
    startDate: `${currentYear}-01-12`,
    totalCycles: 12,
    dueDay: 12,
    paymentMethod: 'Bank Transfer',
    reminderDaysBefore: 5,
    status: 'active',
    createdAt: `${currentYear}-01-01`,
    cycles: [
      {
        id: 'c_rent_1',
        paymentPlanId: 'plan_rent',
        cycleNumber: 8,
        dueDate: `${currentYear}-${currentMonth}-12`,
        amount: 10000,
        status: 'due_soon',
        paymentMethod: 'Bank Transfer',
      },
    ],
  },
  {
    id: 'plan_family_pool',
    userId: 'user_sourav_1',
    title: 'Family Monthly Pool',
    description: 'Shared family household contribution',
    amount: 3000,
    category: 'contribution',
    frequency: 'monthly',
    startDate: `${currentYear}-01-15`,
    totalCycles: 12,
    dueDay: 15,
    paymentMethod: 'UPI',
    reminderDaysBefore: 3,
    status: 'active',
    createdAt: `${currentYear}-01-01`,
    cycles: [
      {
        id: 'c_family_1',
        paymentPlanId: 'plan_family_pool',
        cycleNumber: 8,
        dueDate: `${currentYear}-${currentMonth}-15`,
        amount: 3000,
        status: 'upcoming',
        paymentMethod: 'UPI',
      },
    ],
  },
  {
    id: 'plan_internet',
    userId: 'user_sourav_1',
    title: 'Internet Fiber',
    description: 'Airtel Xstream Fiber 200Mbps',
    amount: 799,
    category: 'utility',
    frequency: 'monthly',
    startDate: `${currentYear}-01-18`,
    totalCycles: 12,
    dueDay: 18,
    paymentMethod: 'Auto Debit',
    reminderDaysBefore: 2,
    status: 'active',
    createdAt: `${currentYear}-01-01`,
    cycles: [
      {
        id: 'c_net_1',
        paymentPlanId: 'plan_internet',
        cycleNumber: 8,
        dueDate: `${currentYear}-${currentMonth}-18`,
        amount: 799,
        status: 'upcoming',
        paymentMethod: 'Auto Debit',
      },
    ],
  },
  {
    id: 'plan_insurance',
    userId: 'user_sourav_1',
    title: 'Health Insurance',
    description: 'Star Health Family Optima',
    amount: 2000,
    category: 'insurance',
    frequency: 'monthly',
    startDate: `${currentYear}-01-25`,
    totalCycles: 12,
    dueDay: 25,
    paymentMethod: 'Card',
    reminderDaysBefore: 4,
    status: 'active',
    createdAt: `${currentYear}-01-01`,
    cycles: [
      {
        id: 'c_ins_1',
        paymentPlanId: 'plan_insurance',
        cycleNumber: 8,
        dueDate: `${currentYear}-${currentMonth}-25`,
        amount: 2000,
        status: 'upcoming',
        paymentMethod: 'Card',
      },
    ],
  },
];

export const INITIAL_CIRCLES: MoneyCircle[] = [
  {
    id: 'circle_family',
    name: 'Family Monthly Pool',
    description: 'Joint fund for household grocery and utilities',
    targetAmount: 20000,
    collectedAmount: 18000,
    frequency: 'monthly',
    dueDay: 15,
    dueDate: `${currentYear}-${currentMonth}-15`,
    category: 'Family',
    createdAt: `${currentYear}-01-01`,
    members: [
      {
        id: 'm1',
        name: 'Sourav',
        expectedAmount: 5000,
        paidAmount: 5000,
        status: 'paid',
        lastPaymentDate: `${currentYear}-${currentMonth}-02`,
        history: [
          { month: 'Jun', amount: 5000, status: 'paid', date: '2026-06-03' },
          { month: 'Jul', amount: 5000, status: 'paid', date: '2026-07-04' },
          { month: 'Aug', amount: 5000, status: 'paid', date: '2026-08-02' },
        ],
      },
      {
        id: 'm2',
        name: 'Rahul',
        expectedAmount: 5000,
        paidAmount: 5000,
        status: 'paid',
        lastPaymentDate: `${currentYear}-${currentMonth}-05`,
        history: [
          { month: 'Jun', amount: 5000, status: 'paid', date: '2026-06-05' },
          { month: 'Jul', amount: 5000, status: 'paid', date: '2026-07-05' },
          { month: 'Aug', amount: 5000, status: 'paid', date: '2026-08-05' },
        ],
      },
      {
        id: 'm3',
        name: 'Mom',
        expectedAmount: 5000,
        paidAmount: 5000,
        status: 'paid',
        lastPaymentDate: `${currentYear}-${currentMonth}-01`,
        history: [
          { month: 'Jun', amount: 5000, status: 'paid', date: '2026-06-01' },
          { month: 'Jul', amount: 5000, status: 'paid', date: '2026-07-01' },
          { month: 'Aug', amount: 5000, status: 'paid', date: '2026-08-01' },
        ],
      },
      {
        id: 'm4',
        name: 'Dad',
        expectedAmount: 5000,
        paidAmount: 3000,
        status: 'pending',
        lastPaymentDate: `${currentYear}-${currentMonth}-08`,
        history: [
          { month: 'Jun', amount: 5000, status: 'paid', date: '2026-06-10' },
          { month: 'Jul', amount: 5000, status: 'paid', date: '2026-07-09' },
          { month: 'Aug', amount: 3000, status: 'pending', date: '2026-08-08' },
        ],
      },
    ],
  },
  {
    id: 'circle_flat',
    name: 'Flat Expenses',
    description: 'Apartment maintenance, cook & maid pool',
    targetAmount: 10000,
    collectedAmount: 7500,
    frequency: 'monthly',
    dueDay: 12,
    dueDate: `${currentYear}-${currentMonth}-12`,
    category: 'Roommates',
    createdAt: `${currentYear}-02-01`,
    members: [
      { id: 'fm1', name: 'Sourav', expectedAmount: 2500, paidAmount: 2500, status: 'paid', history: [] },
      { id: 'fm2', name: 'Aman', expectedAmount: 2500, paidAmount: 2500, status: 'paid', history: [] },
      { id: 'fm3', name: 'Rohit', expectedAmount: 2500, paidAmount: 2500, status: 'paid', history: [] },
      { id: 'fm4', name: 'Vikash', expectedAmount: 2500, paidAmount: 0, status: 'pending', history: [] },
    ],
  },
];

export const INITIAL_GOALS: SavingsGoal[] = [
  {
    id: 'goal_emergency',
    title: 'Emergency Fund',
    targetAmount: 50000,
    currentAmount: 28000,
    targetDate: `${currentYear}-12-31`,
    monthlyContribution: 5500,
    category: 'emergency',
    createdAt: `${currentYear}-01-15`,
    transactions: [
      { id: 'tx_1', goalId: 'goal_emergency', amount: 5000, type: 'deposit', date: '2026-06-01', note: 'Monthly saving' },
      { id: 'tx_2', goalId: 'goal_emergency', amount: 5000, type: 'deposit', date: '2026-07-01', note: 'Monthly saving' },
      { id: 'tx_3', goalId: 'goal_emergency', amount: 3000, type: 'deposit', date: '2026-08-05', note: 'Bonus deposit' },
    ],
  },
  {
    id: 'goal_laptop',
    title: 'New Laptop',
    targetAmount: 80000,
    currentAmount: 35000,
    targetDate: `${currentYear}-11-15`,
    monthlyContribution: 7500,
    category: 'gadget',
    createdAt: `${currentYear}-02-10`,
    transactions: [
      { id: 'tx_4', goalId: 'goal_laptop', amount: 10000, type: 'deposit', date: '2026-07-15', note: 'Project milestone' },
    ],
  },
  {
    id: 'goal_vacation',
    title: 'Goa Vacation',
    targetAmount: 30000,
    currentAmount: 12000,
    targetDate: `${currentYear + 1}-01-20`,
    monthlyContribution: 3000,
    category: 'travel',
    createdAt: `${currentYear}-03-01`,
    transactions: [
      { id: 'tx_5', goalId: 'goal_vacation', amount: 4000, type: 'deposit', date: '2026-08-01', note: 'Travel savings' },
    ],
  },
];

export const INITIAL_ACHIEVEMENTS: SavingsAchievement[] = [
  { id: 'ach_1', title: 'First ₹10K Saved', description: 'Crossed the 10,000 milestone', icon: '🏆', unlocked: true, unlockedAt: '2026-04-10' },
  { id: 'ach_2', title: '3-Month Streak', description: 'Saved consistently for 3 months', icon: '🔥', unlocked: true, unlockedAt: '2026-05-01' },
  { id: 'ach_3', title: 'Paid Every Month On Time', description: 'Zero delayed payments', icon: '⚡', unlocked: true, unlockedAt: '2026-06-30' },
  { id: 'ach_4', title: '₹50K Emergency Fund', description: 'Build a safety cushion', icon: '🛡️', unlocked: false },
  { id: 'ach_5', title: 'Circle Champion', description: 'Completed all circle payments', icon: '🤝', unlocked: true, unlockedAt: '2026-07-15' },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    type: 'PAYMENT_DUE',
    title: 'Payment due soon',
    message: 'Bike EMI of ₹5,000 is due in 4 days.',
    date: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    read: false,
    relatedEntityId: 'plan_bike_emi',
    relatedEntityType: 'payment',
  },
  {
    id: 'notif_2',
    type: 'CIRCLE_MEMBER_PAID',
    title: 'Rahul paid contribution',
    message: 'Rahul paid ₹5,000 to Family Monthly Pool.',
    date: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    read: false,
    relatedEntityId: 'circle_family',
    relatedEntityType: 'circle',
  },
  {
    id: 'notif_3',
    type: 'PAYMENT_PAID',
    title: 'Payment recorded',
    message: 'Previous cycle for Bike EMI was confirmed via UPI.',
    date: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    read: true,
    relatedEntityId: 'plan_bike_emi',
    relatedEntityType: 'payment',
  },
  {
    id: 'notif_4',
    type: 'CIRCLE_MEMBER_PENDING',
    title: 'Contribution pending',
    message: "Dad's contribution of ₹2,000 is pending in Family Pool.",
    date: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    read: true,
    relatedEntityId: 'circle_family',
    relatedEntityType: 'circle',
  },
];
